name: mlflow_project

python: "3.10"
pip_requirements: requirements.txt

entry_points:
  main:
    parameters:
      data_path: {type: str, default: "data_clean.csv"}
    command: "python modelling.py --data_path {data_path}"
